name: "pipeline"
on: [workflow_dispatch]
jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4.2.2
  setup:
    runs-on: ubuntu-latest
    needs: [checkout]
    steps:
      - name: Setup Node 20 environment
        uses: actions/setup-node@v3.9.1
        with:
          node-version: '20'

  install:
    runs-on: ubuntu-latest
    needs: [setup]
    steps:
      - name: Install dependencies
        run: yarn install

  build:
    runs-on: ubuntu-latest
    needs: [install]
    steps:
      - name: Build
        run: yarn build

  unit-tests:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Unit tests
        run: yarn test
        continue-on-error: true

  integration-tests:
    runs-on: ubuntu-latest
    needs: [unit-tests]
    steps:
      - name: Integration tests
        run: yarn test:e2e
        continue-on-error: true

  junit-report:
    runs-on: ubuntu-latest
    needs: [integration-tests]
    steps:
      - name: JUnit Report Action
        uses: mikepenz/action-junit-report@v5.2.0
        with:
          report_paths: reports/*.xml
  
      
        
    
